service: hisaabkitaab-serverless-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  profile: aws_cli_development_profile

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  # index:
  #   handler: dist/index.handler
  #   events:
  #   - http:
  #       cors: true
  #       path: '/items'
  #       method: get
  # createItem:
  #   handler: dist/index.handler
  #   events:
  #   - http:
  #       cors: true
  #       path: '/item'
  #       method: post
  # updateItem:
  #   handler: dist/index.handler
  #   events:
  #   - http:
  #       cors: true
  #       path: '/item'
  #       method: patch
  # deleteItem:
  #   handler: dist/index.handler
  #   events:
  #   - http:
  #       cors: true
  #       path: '/item'
  #       method: delete
    
    # - http:
    #     cors: true
    #     path: '{proxy+}'
    #     method: any
  index:
      handler: dist/index.handler
      events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any